default_language_version:
    python: python3.7

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: check-added-large-files
        -   id: check-docstring-first
        -   id: detect-private-key
    -   repo: https://github.com/psf/black
        rev: 19.3b0
        hooks:
        -   id: black
    -   repo: https://github.com/PyCQA/pylint
        rev: ''
        hooks:
        -   id: pylint
            args:
            -   --ignored-modules=tensorflow.keras
            -   --ignored-modules=tensorflow
            -   --const-naming-style=UPPER_CASE
            -   --attr-naming-style=UPPER_CASE
    -   repo: https://github.com/myint/docformatter
        rev: ''
        hooks:
        -   id: docformatter
